name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 270
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: Set up Git
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials

      - name: Clone repository
        run: |
          git clone -b main https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} ${{ secrets.GIT_NAME }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Bot
        run: |
          cd ${{ secrets.GIT_NAME }}
          brew install ffmpeg libmagic
          pip install -r requirements.txt
          pip cache purge
          bash run.sh

      - name: Loop workflow
        run: |
          git clone -b main https://${{ secrets.SUPER_TOKEN }}@github.com/${{ github.repository }} loop
          cd loop || exit 1
          echo $(( RANDOM - (RANDOM % RANDOM) )) > looper.txt
          git add looper.txt
          git commit -m "Run Tests: Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${{ github.repository }} HEAD:main
