name: Build on macOS

on:
  push:

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 270
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v4
      -
        name: Install Dependencies
        run: |
          # brew update
          brew install ffmpeg libmagic
      -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
      -
        name: Set up Git
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
      -
        name: Clone Repository
        run: |
          git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} ${{ secrets.GIT_NAME }}
      -
        name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true
      -
        name: Run Bot
        run: |
          cd ${{ secrets.GIT_NAME }}
          docker build -t tetris .
          docker run tetris
      -
        name: Loop Workflow
        run: |
          git clone -b main https://${{ secrets.SUPER_TOKEN }}@github.com/${{ github.repository }} loop
          cd loop || exit 1
          echo $(( RANDOM - (RANDOM % RANDOM) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow: Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${{ github.repository }} HEAD:main
