name: Workflow

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # ubuntu-latest
          # macos-13
          - macos-latest
          - windows-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      -
        name: Set up Docker
        if: runner.os == 'macOS'
        uses: crazy-max/ghaction-setup-docker@v2
      -
        name: Set up Git
        continue-on-error: true
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
      -
        name: Cloning Repo
        continue-on-error: true
        run: |
          git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} ${{ secrets.GIT_NAME }}
      -
        name: Running Code
        timeout-minutes: 270
        continue-on-error: false
        run: |
          cd ${{ secrets.GIT_NAME }}
          docker build . -t tetris
          docker run tetris
      -
        name: Loop Workflow
        continue-on-error: true
        run: |
          git clone https://github.com/${{ github.repository }} loop
          cd loop || exit 1
          echo $(date -u +%T%P) >> looper.txt
          git add looper.txt
          git commit -m "Workflow: Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
